services:
  - type: web
    name: rentmatch
    env: native
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: OPENCAGE_API_KEY
        sync: false